# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Configurar JDK 1.8 utilizando setup-java@v1 para AdoptOpenJDK
- task: UseJavaVersion@1
  inputs:
    versionSpec: '1.8'
    jdkArchitecture: 'x64'

# Limpiar caché de Maven (opcional pero recomendado)
- script: |
    rm -rf ~/.m2/repository
  displayName: 'Clear Maven Cache'

# Compilar el proyecto con Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'path'       # Usa la versión de JAVA_HOME configurada en el paso anterior
    jdkDirectory: $(JAVA_HOME)   # Establece JAVA_HOME desde UseJavaVersion
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
