trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseJavaVersion@1
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'  # Debe coincidir con la versión configurada arriba
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: CopyFiles@2
  displayName: 'Copy Files to artifact staging directory'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/target/*.?(war|jar)'
    TargetFolder: $(Build.ArtifactStagingDirectory)

- publish: $(Build.ArtifactStagingDirectory)
  artifact: drop
