# Azure DevOps pipeline configuration for Java and Maven project

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Paso para instalar JDK 1.8 desde el almacenamiento de Azure si no está preinstalado
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '1.8'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'AzureStorage'  # Descarga JDK desde Azure Storage si no está preinstalado

# Limpiar caché de Maven (opcional)
- script: |
    rm -rf ~/.m2/repository
  displayName: 'Clear Maven Cache'

# Compilar y empaquetar el proyecto con Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'

# Copiar artefactos (WAR/JAR) generados en la etapa de construcción
- task: CopyFiles@2
  displayName: 'Copy Files to artifact staging directory'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/target/*.war'
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'drop'
